applicationId=com.MiddleFrame.Tictactoe
appName=Tic tac toe
versionName=0.7.2
versionCode=42
minSdk=25
targetSdk=36
compileSdk=36
abiFilters=armeabi-v7a,arm64-v8a
keyAlias=tttp
keystoreFile=private/karasique.keystore
