applicationId=com.MiddleFrame.Tictactoe
appName=Tic tac toe
serverUrl=https://tic-tac-toe-plus-alpha.stofs.chatgpt.site
versionName=0.7.1
versionCode=33
minSdk=25
targetSdk=36
compileSdk=36
abiFilters=armeabi-v7a,arm64-v8a
keyAlias=tttp
keystoreFile=private/karasique.keystore
