export const progressionCopy = {
  ru: {
    passes: "Пути коллекций", level: "Уровень", xp: "опыта", free: "Бесплатно", premium: "Премиум",
    claim: "Забрать", claimed: "Получено", locked: "Закрыто", rewardReady: "Есть награды",
    claiming: "Получаем…", rewardReceived: "Награда получена", rewardsReceived: "Награды получены", coinsReceived: "монет",
    current: "Сейчас", premiumLocked: "Нужен премиум", levelRequired: "Нужен уровень", progressSummary: "Прогресс коллекции",
    readyCount: "Можно забрать", nextReward: "Следующая награда", allRewardsReached: "Все уровни достигнуты", showNearest: "К прогрессу",
    claimAll: "Забрать всё", nextLevel: "Следующий уровень", legacyRewards: "Награды до обновления",
    noReward: "Пока без награды", comingLater: "Добавим позже", rewardsPlaceholder: "Награды ещё в разработке. Уровни и опыт сохраняются.",
    cardOpening: "Анимация открытия", cardAppearance: "Внешний вид карты", placementAnimation: "Анимация постановки", boardAnimation: "Анимация фигуры",
    testPremium: "Открыть премиум · тест", testNotice: "Тестовый доступ бесплатен. Покупка пасса появится позже.",
    remaining: "Осталось открыть", duplicates: "Повторки превращаются в 30 опыта своей коллекции.",
    dust: "Повторка · превращаем в опыт", buyAgain: "Купить ещё одну", done: "Готово", collection: "В коллекцию",
    newDeck: "Новая колода", deckName: "Название колоды", deleteDeck: "Удалить колоду", deckSelect: "Активная колода",
    deckRule: "Обычные карты + одна стихия. Новые карты добавляйте в выбранную колоду самостоятельно.",
    failed: "Не удалось сохранить. Повторите попытку.", retry: "Повторить", xpPending: "Сохраняем опыт…",
    xpUnavailable: "Опыт пока не сохранён. Нужно подключение.", maxLevel: "Максимальный уровень", completed: "Коллекция собрана",
    roundXp: "Опыт за раунд", noXp: "Ничья: опыт не начисляется", roundRules: "За каждый экземпляр карты: победа в раунде — 3 опыта, поражение — 1. Стоимость уровней постепенно растёт.",
    forfeit: "За выход из матча опыт пока не начисляется", passOf: "Путь коллекции", buy: "Купить", cards: "карт",
  },
  en: {
    passes: "Collection paths", level: "Level", xp: "XP", free: "Free", premium: "Premium",
    claim: "Claim", claimed: "Claimed", locked: "Locked", rewardReady: "Rewards available",
    claiming: "Claiming…", rewardReceived: "Reward claimed", rewardsReceived: "Rewards claimed", coinsReceived: "coins",
    current: "Current", premiumLocked: "Premium required", levelRequired: "Requires level", progressSummary: "Collection progress",
    readyCount: "Ready to claim", nextReward: "Next reward", allRewardsReached: "All levels reached", showNearest: "Show progress",
    claimAll: "Claim all", nextLevel: "Next level", legacyRewards: "Rewards earned before the update",
    noReward: "No reward yet", comingLater: "Coming later", rewardsPlaceholder: "Rewards are still in development. Your levels and XP are saved.",
    cardOpening: "Opening animation", cardAppearance: "Card appearance", placementAnimation: "Placement animation", boardAnimation: "Piece animation",
    testPremium: "Unlock premium · test", testNotice: "Test access is free. Pass purchases will arrive later.",
    remaining: "Left to discover", duplicates: "Duplicates turn into 30 XP for their collection.",
    dust: "Duplicate · turning into XP", buyAgain: "Buy another card", done: "Done", collection: "To collection",
    newDeck: "New deck", deckName: "Deck name", deleteDeck: "Delete deck", deckSelect: "Active deck",
    deckRule: "Regular cards + one element. Add new cards to your chosen deck yourself.",
    failed: "Could not save. Please try again.", retry: "Retry", xpPending: "Saving XP…",
    xpUnavailable: "XP has not been saved yet. Connection required.", maxLevel: "Maximum level", completed: "Collection complete",
    roundXp: "Round XP", noXp: "Draw: no XP awarded", roundRules: "Per card copy: round win — 3 XP, loss — 1 XP. Level costs gradually increase.",
    forfeit: "Leaving a match does not award XP yet", passOf: "Collection path", buy: "Buy", cards: "cards",
  },
};
